version: '3.8'
services:
  squid:
    image: ${PROXY_IMAGE}
    container_name: squid
#   build:
#     context: .
#     dockerfile: Dockerfile
    ports:
      - "3128:3128"
    volumes:
      - type: bind
        source: ./config/squid.conf
        target: /etc/squid/squid.conf
    logging:
      driver: syslog
      options:
        tag: '{{.Name}}'
    restart: always

networks:
  default:
    name: core_nw
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: core_nw
    ipam:
     driver: default
     config:
       - subnet: 10.0.0.0/24

# docker build -t tag:version .
# docker-compose up --build